# Generated by Django 5.1.6 on 2025-05-17 21:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_user', models.IntegerField(unique=True)),
                ('login_status', models.CharField(choices=[('Logout', 'Logout'), ('Login', 'Login')], default='Login', max_length=10)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Worker', 'Worker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Cameroon', max_length=60)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/offer/')),
                ('upload_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offre.person')),
            ],
            bases=('offre.person',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offre.person')),
            ],
            bases=('offre.person',),
        ),
        migrations.CreateModel(
            name='WorkOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=255)),
                ('offer_description', models.TextField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('offer_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20)),
                ('post_at', models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 51, 39, 849951, tzinfo=datetime.timezone.utc))),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('list_of_media', models.ManyToManyField(blank=True, to='offre.media')),
                ('offer_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offre.location')),
                ('customer_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 51, 39, 852383, tzinfo=datetime.timezone.utc))),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Validated', 'Validated')], default='Pending', max_length=20)),
                ('attach_files', models.ManyToManyField(blank=True, null=True, to='offre.media')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.workoffer')),
                ('worker_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.worker')),
            ],
        ),
    ]
