# Generated by Django 5.1.6 on 2025-05-18 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='number_of_worker',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 18, 24, 8, 878722, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 18, 24, 8, 876311, tzinfo=datetime.timezone.utc)),
        ),
    ]
