# Generated by Django 5.1.6 on 2025-05-18 19:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0002_workoffer_number_of_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='work_domain',
            field=models.CharField(default='Electronic', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 27, 1, 187436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 27, 1, 185076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_recommendation', models.FloatField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.workoffer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.worker')),
            ],
        ),
    ]
