# Generated by Django 5.1.6 on 2025-05-18 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0003_workoffer_work_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 29, 48, 138135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 29, 48, 135778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='work_domain',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
