# Generated by Django 5.1.6 on 2025-05-18 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0004_alter_offerapplication_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 20, 1, 31, 498377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 20, 1, 31, 495902, tzinfo=datetime.timezone.utc)),
        ),
    ]
