# Generated by Django 5.1.6 on 2025-05-19 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0005_alter_offerapplication_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 17, 5, 26, 228909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 17, 5, 26, 226683, tzinfo=datetime.timezone.utc)),
        ),
    ]
