# Generated by Django 5.1.6 on 2025-05-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0006_alter_offerapplication_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapplication',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 17, 34, 30, 465748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 17, 34, 30, 463344, tzinfo=datetime.timezone.utc)),
        ),
    ]
