# Generated by Django 5.1.6 on 2025-05-16 15:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_user', models.IntegerField(unique=True)),
                ('login_status', models.CharField(choices=[('Logout', 'Logout'), ('Login', 'Login')], default='Login', max_length=10)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Worker', 'Worker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/publication/')),
                ('upload_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.person')),
            ],
            bases=('publication.person',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.person')),
            ],
            bases=('publication.person',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_publication', models.TextField()),
                ('post_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.BooleanField(default=False)),
                ('medias', models.ManyToManyField(blank=True, to='publication.media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_at', models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 22, 2, 405380))),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('post_at', models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 22, 2, 404762))),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_preferences', models.FloatField(default=0.0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Screen_Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_at', models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 22, 2, 406332))),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.person')),
            ],
        ),
    ]
