# Generated by Django 5.1.6 on 2025-05-16 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 25, 53, 797388, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 25, 53, 798821, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 15, 25, 53, 799619, tzinfo=datetime.timezone.utc)),
        ),
    ]
