# Generated by Django 5.1.6 on 2025-05-16 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_comment_post_at_alter_like_post_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 15, 27, 913076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 15, 27, 913709, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 15, 27, 910981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 18, 15, 27, 914353, tzinfo=datetime.timezone.utc)),
        ),
    ]
