# Generated by Django 5.1.6 on 2025-05-17 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_comment_post_at_alter_like_post_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 8, 21, 317651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 8, 21, 318286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 8, 21, 315548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 8, 21, 318929, tzinfo=datetime.timezone.utc)),
        ),
    ]
