# Generated by Django 5.1.6 on 2025-05-17 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_comment_post_at_alter_like_post_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen_print',
            name='post_at',
        ),
        migrations.AddField(
            model_name='screen_print',
            name='view_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 31, 22, 153463, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 31, 22, 152213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 31, 22, 152832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 8, 31, 22, 149953, tzinfo=datetime.timezone.utc)),
        ),
    ]
