# Generated by Django 5.1.6 on 2025-05-17 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_remove_screen_print_post_at_screen_print_view_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_value',
            field=models.CharField(choices=[('Aimer', 'Aimer'), ('Neutre', 'Neutre'), ('Detester', 'Detester')], default='Neutre', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 20, 12, 51, 403925, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 20, 12, 51, 404549, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 20, 12, 51, 401628, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='view_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 20, 12, 51, 405392, tzinfo=datetime.timezone.utc)),
        ),
    ]
