# Generated by Django 5.1.6 on 2025-05-17 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_like_like_value_alter_comment_post_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 56, 55, 726106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_value',
            field=models.CharField(choices=[('Like', 'Like'), ('Neutral', 'Neutral'), ('Hate', 'Hate')], default='Neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 56, 55, 726722, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 56, 55, 723884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='view_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 21, 56, 55, 727565, tzinfo=datetime.timezone.utc)),
        ),
    ]
