# Generated by Django 5.1.6 on 2025-05-18 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_alter_comment_post_at_alter_like_like_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 59, 3, 384477, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 59, 3, 385113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 59, 3, 382400, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='screen_print',
            name='view_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 19, 59, 3, 385832, tzinfo=datetime.timezone.utc)),
        ),
    ]
