# Generated by Django 5.1.6 on 2025-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='user.experience'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, to='user.servicesprovided'),
        ),
    ]
