# Generated by Django 5.1.6 on 2025-05-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_worker_experiences_alter_worker_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experiences',
            field=models.ManyToManyField(blank=True, null=True, to='user.experience'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='user.servicesprovided'),
        ),
    ]
