# Generated by Django 5.1.6 on 2025-05-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_worker_experiences_alter_worker_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Confirmed', 'Confirmed')], default='Unverified', max_length=20),
        ),
    ]
