# Generated by Django 5.1.6 on 2025-05-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_worker_worker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_status',
        ),
        migrations.AddField(
            model_name='experience',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.servicesprovided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
