# Generated by Django 5.1.6 on 2025-06-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_worker_worker_status_experience_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('answer4', models.TextField()),
                ('answer5', models.TextField()),
                ('true_answer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsForService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answers', models.ManyToManyField(to='user.multiplequestionanswer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.servicesprovided')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_marks', models.FloatField(default=0.0)),
                ('evaluation_status', models.CharField(choices=[('Unverified', 'Unverified'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Confirmed', 'Confirmed')], default='Unverified', max_length=20)),
                ('evaluate_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.worker')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.questionsforservice')),
            ],
        ),
    ]
